[tool.poetry]
name = "design-patterns-appied-to-python"
version = "0.1.0"
description = ""
authors = ["Ruud Juffermans"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
